### ISSUE TITLE
WASD Keys aren't working. Only ESC Key works. Please help?

### ISSUE THREAD

**Issue by mlw836** [ElDewrito/ElDorito#154]
### Guidelines
- Your title should clearly describe the issue.
- Describe the exact steps you took before the problem arose.
- Give us as much info about your install as you can. List any mods you have installed and state where you downloaded ElDewrito from (without providing a link).

### How can the issue be reproduced?
Please be as descriptive as possible.

1.

2.

3.

**Comment by medsouz** [comment]
Go into the settings screen and check if your input is set to controller instead of keyboard.

**Comment by Shockfire** [comment]
Please fill out the issue template if you want to be taken seriously. Issues like this should be fixed with the next update, which makes some major improvements to input binding. To solve your problem right now, generally you need to open the keyboard bindings menu and then close it again to make them apply.
