### ISSUE TITLE
Web Renderer secure origin

### ISSUE THREAD

**Issue by maximumgame** [ElDewrito/ElDorito#155]
Local files are not treated as secure and neither are https:// or dew:// schemes. Normally chrome would see local files and https as secure.

As such, loading an https site and trying to load a dew:// scheme from the page will block the request for mixed content. And navigator.getUserMedia will not work either locally or from the web since it requires a secure origin. (sidenote: if getUserMedia were to work, we'd need a permission dialog for the user to accept)

**Comment by Shockfire** [comment]
CEF doesn't currently support this feature. There is an [open issue](https://bitbucket.org/chromiumembedded/cef/issues/1723/register-internal-schemes-as-secure-to) requesting it to be added, but nothing has been done about it yet. The recommended workaround seems to be to intercept https:// requests and forward a certain domain name to the filesystem, but this seems to me like it would complicate things unless it's absolutely necessary to do.

In general we don't recommend that you try to load screens remotely. The only reason it's supported is so that the Game.MenuURL variable can still work. Anvil's web renderer will require all content to be loaded locally.

Is there something specific you want to do that requires this functionality?

**Comment by maximumgame** [comment]
I was only attempting to get microphone input from a local screen and when it failed I thought I'd try over https. Obviously not a major issue.

**Comment by Shockfire** [comment]
Yeah, I would say that microphone input is outside the scope of what the web renderer is intended for. It's mostly just supposed to be a thin layer on top of the game which is purely responsible for displaying a GUI. Any special logic not directly related to the user interface should just be done with native code.
