### ISSUE TITLE
{FORGE} Ideas & Issues

### ISSUE THREAD

**Issue by ghost** [ElDewrito/ElDorito#166]
1. Can you make the "Breakable crates" look slightly different from the solid crates by marking it with yellow in the corners or something to let people know they can break them. There have been maps where it requires people to break them but they don't know this as they look the same.
2. An option to turn off the mines on Sandtrap could be useful for some people.
3. Will the spawn areas be fixed in the new update? You have to place up-to 32 spawn points for Infection (16 for attackers, 16 for defenders) and they take up your limit in Forge which could be used on more useful things like objects or weapons. By Having the spawn areas working it would only take up 2 (Limit) for both sides.

**Comment by surprise0451** [comment]
1.Breakable crates can't look different because they share the same textures and models.

2. They can't make an option for it, but what they could do is have two separate map files for this. 

3. Probably not.

**Comment by ihatecompvir** [comment]
I wouldn't necessarily say that disabling Sandtrap mines would require two different maps. We could technically do it in a very similar fashion to the disabling of the map barriers. It would expand the playable/Forgeable Sandtrap area quite a bit.

Breakable crates could also *technically* be changed, but it would require a new object otherwise all of those crates would have the same texture and model, breaking old Forge maps.

Spawn areas, I'm not sure. I thought they already worked.

**Comment by scooterpsu** [comment]
Spawn areas are fixed in 0.6 and the Sandtrap "defenders" (egg at each tower) can be removed (disabling mines). That was the majority of this, so I'm going to close it.
