### ISSUE TITLE
Make updater configurable

### ISSUE THREAD

**Issue by kiwidoggie** [ElDewrito/ElDorito#54]
Currently, the updater makes a few assumptions about layout etc.

First, updater when combined with the build flag (-b "<directory path without trailing slash>") only writes the manifest to it's local directory/manifest.json. This should be allowed to be placed anywhere.
The manifest link is currently harcoded, but should also allowed to be overridden by a config or flag.
The client hook path is also currently hardcoded (mtndew.dll) but should be allowed to be overridden by a config or a flag.

**Comment by kiwidoggie** [comment]
Possibly going to implement a -u flag for specifying a manifest on another server than default (would be good to point to a different server), or even -c for cluster of servers, try them all until one works.

**Comment by emoose** [comment]
Is this the updater we're currently using? I don't remember it using any manifest.json files, but then again I haven't touched the updater in some time.

For DR I was planning on scrapping the launcher/updater and having an UpdaterPlugin which verifies game files and checks for updates, if it finds one then it'd prompt the user, exit and run a DewritoUpdateHelper.exe which would perform the actual update (just a small program with a progress bar and some logging)

I was also going to change the format of some of the server-side JSON files, along with having signed update manifests (which allows us to support multiple update servers, since we can be sure the updates haven't been tampered with via the hashes in the manifests).

Was also thinking of a system to allow others to push to their own updater branches via signed pubkey files, ie. we'd sign their public key manifest (which details the public key itself/branch name/issue date/expiry date) with our master key, and then they can sign their own manifests. That way we can let any dev push to the beta branch, while only the trusted few with the master key can push to the stable one.

I did a few drafts of the server-side files needed for this, haven't actually started on any code though. I can upload the drafts somewhere if anyones interested.

**Comment by kiwidoggie** [comment]
This is for the current updater, that is in my Beta branch. The new launcher/updater and menu proof of concept code has been uploaded to github.

**Comment by kiwidoggie** [comment]
Closing issue because ElDorito is finished development.
