### ISSUE TITLE
Git Structure

### ISSUE THREAD

**Issue by kiwidoggie** [ElDewrito/ElDorito#60]
I think we should change the way that we are using git.

master - for production builds, what user's will automatically get rolled out to them

development - indev, **WORKING** builds, with new features and lightly tested functionality

feature/<feature name> - burn branches, builds in here may or may not compile etc, your "I'm currently working on it branch", these should be closed once a feature makes it to master.

bugfix/<bugfix name> - Bugfix branches, while testing patches and fixes should be done here if they are major bugs (like rendering issues etc), these should be merged back into development then left to go stale or closed.

Any others/questions/concerns?

**Comment by no1dead** [comment]
nope this is a good way of doing things.

**Comment by HaydnTrigg** [comment]
I can't support such a sensible argument.

**Comment by emoose** [comment]
I agree the git needs reorganizing, but that doesn't really follow how I seen most gits setup though. DewRecode is following this style: (which I mostly borrowed from https://wiki.openmw.org/index.php?title=Branching_Policy)

Master is for the latest, bleeding edge code. I've barely seen any gits setup where master isn't the latest code. Makes things a lot easier too since github usually associates master with the latest code (eg when doing pull requests it selects master by default)

Production builds are branched off from there when a release is approaching, and testing is done with this release branch. Fixes get applied to this branch and testing continues, eventually when the release is made (on the main channel) the branch gets merged back into master and the latest commit is tagged with the release version number. (eg see: https://github.com/ElDewrito/ElDorito/releases, although it seems people forgot to tag these recent rushed updates...)

The feature and bugfix branches are a good idea, I was thinking of something similar. Chances are we wouldn't really have them in the main repo though, they'd probably be used in your own local repo, but I suppose if you wanted others to contribute you could push them into the main one too.

People who don't have contributor access to the git should fork it into their own github and work on it there, then make a pull request once their changes are ready.

**Comment by emoose** [comment]
Actually disregard what I said above, the structure kiwidoggie suggested could actually be better since it'd let us have a stable branch with the latest code, which people can build knowing that it's safe to use.

It also seems very similar to the Gitflow structure too (https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Though I still think we should branch off when releases are coming up, to help us refrain from bloating/delaying releases with last minute features (as with the case of 0.5..)

**Comment by Limited55** [comment]
I agree with structure of having master always having a working build. Merges into master should only be when you know it is tested and working properly.  I agree with Kiwi when we say to branch off for releases, this will allow features to get tested together prior to releasing to main. 

The idea of having a bugs branch is good, however I also suggest we have a hotfixes branch, that is used to patch the Master branch directly. This is for things such as the descope issue we had where we cannot go back through the development branch as that would include the newer functionality.

When creating a multi-branch workflow it becomes a lot of work to manage, and people doing so will need to be very good at merging and knowing what code is doing what. We'd need to keep on
top of it.

**Comment by kiwidoggie** [comment]
Bugs and Hotfixes are on in the same for my projects. You only create a hotfix/bug-you-are-fixing. And it's not terrible if you know what you are doing :dancers:

**Comment by Limited55** [comment]
Yes but your saying you should merge hotfix back into development branch, which might have stuff not ready to be launched. Hotfixes are as they suggest, fixes they are applied quickly.

**Comment by kiwidoggie** [comment]
You should never work on new features in a hotfix branch. And hotfix branches should only be created for release candidates and launched versions. So if that were to happen it is user error. It really depends on the situation if a hotfix should get merged all the way back into development (is it a bug fix in lets say the core which is used in future versions?, or is this some stupid UI bug that was fixed that is version specific and will get thrown out later, or re-coded)

**Comment by kiwidoggie** [comment]
Closing issue because ElDorito is finished development.
