### ISSUE TITLE
Research use of ingame chat

### ISSUE THREAD

**Issue by kiwidoggie** [ElDewrito/ElDorito#64]
Investigate and research if the use of in-game chat is possible.

**Comment by emoose** [comment]
Our build doesn't have actual ingame chat since it was added in a later HO build, there's only the chat on the mainmenu.
Looking through some of the SSL files it looks like ingame chat could be in here but disabled, might have some things missing too for all we know though.. maybe we could try porting the SSL from the newer builds into this, that might get the ingame chat to work.

**Comment by dark-c0de** [comment]
I've enabled chat by modifying SSL. You can type and hit enter but nothing happens. We could possibly use shocks new packet system to send messages, or the existing ts3 chat api that supports file transfers (bspatch files?)

**Comment by emoose** [comment]
Oh really? Neat, I suppose we'd only have to change a few things in the SSL and hook some things to get it working properly then (afaik right now it's setup to send chat messages to the games actual master server, into a sort of channel setup just for that game)

Using the games networking itself would probably be better, there could be issues connecting to the VoIP, or the host could have VoIP disabled. With the games networking we know if they're connected to the game then we have a working connection to use.

Ideally building VoIP into the games networking too would be the best option, the less ports/connections needed the better, but I guess that'd be pretty hard since TS3 has it's own protocol etc, and I doubt any one of us want to work on our own custom VoIP stuff :P

**Comment by kiwidoggie** [comment]
I would prefer to use shock's system as it is more tied into the engine, and does not require external dependencies.

**Comment by kiwidoggie** [comment]
Closing issue because ElDorito is finished development.
