### ISSUE TITLE
Lua code for medals isn't sandboxed

### ISSUE THREAD

**Issue by Shockfire** [ElDewrito/ElDorito#80]
Was just talking to shad0wshayd3 on IRC and he said he was able to make a "medal pack" which runs dany's sound injector. As cool as that is, code should *not* be allowed to do stuff like that at all.

**Comment by kiwidoggie** [comment]
This should be changed in it's entirety, security should be the forefront of this project since it is free.

**Comment by Shad0wShayd3** [comment]
If it even matters, the lua runs out of C:\Halo and has access to anything that doesn't require admin access by way of batch files, which can be packed into the zip and referenced freely. Not sure how much other stuff the lua can actually do, it does have access to the os module, since I used os.time and os.execute to make the sound injector injector.

**Comment by kiwidoggie** [comment]
You can set up lua bindings to run on only a whitelist (disabling all file io, you can set allowed dirs/files), disable everything system and most common libraries.

**Comment by theTwist84** [comment]
This should with the web-renderer branch.
