### ISSUE TITLE
Ping command doesn't respond via rcon

### ISSUE THREAD

**Issue by scooterpsu** [ElDewrito/ElDorito#95]
If you ping via rcon, the pong ends up in the in-game console.

**Comment by scooterpsu** [comment]
Which sadly leads to this:

http://i.imgur.com/f8TrGQP.jpg

**Comment by ElDewritoDev** [comment]
Well this is a bit of an interesting issue, because it represents a design flaw in the command system. The problem is that the ping command returns immediately after firing off a ping packet, so it doesn't have any output which can get returned back to the RCON interface. Currently, the only proper way for a command to produce output is for it to return it as a string, but commands which run asynchronously can't do this easily. Perhaps we should create some sort of "ConsoleLog" interface class which gets passed to a command when you run it, and all output is done through there instead of by returning something.

**Comment by scooterpsu** [comment]
Ah, in my head it was just a flag on the input indicating rcon, telling it to shoot the output via that channel. That does sound significantly more complicated.

**Comment by emoose** [comment]
>Perhaps we should create some sort of "ConsoleLog" interface class which gets passed to a command when you run it, and all output is done through there instead of by returning something

I was thinking of something like this too, maybe instead of the returnInfo string we should have a sort of ICommandContext ref instead, then we could have LogFileContext/ConsoleContext/RemoteConsoleContext classes which would send the output to the right place.

LogFile and Console classes would be made when ED inits, while RemoteConsole contexts would be made when someone connects to the rcon port, with fields for the proper socket etc. Could probably move some of the rcon handling code to the context too, would probably also make password-protected rcon a lot easier to implement since the context could hold the state for that connection (isAuthenticated etc)
